try {
  test();
} catch (error) {
  console.log(error);
}
